[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "dbus",
  "fontconfig",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb"
]

[start]
cmd = "node server.js"
